### PR TITLE
Move the tfstate-backend module to its own repo

### PR DESCRIPTION
**Pull request by RothAndrew**

### CODE REVIEW

**Comment by brianrexrode** [comment]
would it make sense to go ahead and create the new tf-state repo, create an initial tag and add that to the main.tf in the examples folders to point to the new repo:tag as part of this PR?

**Comment by RothAndrew** [comment]
I'd prefer to keep this PR small, but I'd be happy to do that immediately after we go ahead and pull the trigger on making this decision (signified by getting this PR approved and merged)

**Review by brianrexrode — APPROVED** [review]
👍

**Comment by RothAndrew** [comment]
Looking for at least 1 more approval before I merge since this signifies a decision we are making as a team.

**Review by ntwkninja — APPROVED** [review]
agree with this direction

As we relocate modules to their own repositories, I think it would be useful to repurpose this repo as `aws-iac-examples` and keep it updated as we relocate interdependent modules to their own GitHub repositories (similar to BB umbrella concept).

**Pull request merged**
